spring.application.name=planning-formation

# PORT SERVEUR
server.port=8080

# CONNEXION BDD MARIA DB
spring.datasource.url=jdbc:mariadb://localhost:3306/gestion_formations?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# CONFIG JPA / HIBERNATE   
spring.jpa.hibernate.ddl-auto=update  
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

# CHARSET
spring.datasource.hikari.connection-init-sql=SET NAMES utf8mb4

# JSON dates lisibles
spring.jackson.serialization.WRITE_DATES_AS_TIMESTAMPS=false

# CORS simple pour le front React (port 5173 si Vite, 3000 si CRA)
app.cors.allowed-origins=http://localhost:5173,http://localhost:3000

# CONFIG DEVTOOLS (rechargement automatique)
spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true

# ===== JWT (DEV) =====
# Clé DEV en Base64 (exemple). Tu peux la garder pour démarrer.
app.jwt.secret=QW5ZdWx0cmFfU2VjcmV0X0Jhc2U2NF80MkJ5dGVzX2Zvcl9ERUY=
app.jwt.exp-minutes=480
# ===== CORS Spring Boot 3 pour Vite (5173) =====
spring.web.cors.allowed-origins=http://localhost:5173
spring.web.cors.allowed-methods=GET,POST,PUT,PATCH,DELETE,OPTIONS
spring.web.cors.allowed-headers=*
spring.web.cors.exposed-headers=Authorization
spring.web.cors.allow-credentials=false


#afci.upload.root=/var/afci-uploads
afci.upload.root=D:/afci-uploads
afci.upload.users-dir=${afci.upload.root}/users
afci.upload.evidences-dir=${afci.upload.root}/evidences
# Limites recommandées
spring.servlet.multipart.max-file-size=6MB
spring.servlet.multipart.max-request-size=6MB

# base URLs utilisées pour construire/rediriger les liens
app.api.base-url=http://localhost:8080
app.front.base-url=http://localhost:5173

# durée de vie du lien de vérification (minutes)
app.email.verify.exp-minutes=1440

# nos classes
logging.level.com.afci.training.planning=DEBUG

# (optionnel) voir le SQL
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE

